/*
   Package indicators provides wrapped indicator functions
   that can be called from go.

   Internally it uses `indicatorData` helper in util.go to
   handle data unwrapping and wrapping between C and go.

   Each indicator functions is generated by parsing the
   indicator list on https://tulipindicators.org/list.
*/
package indicators
